# Generated by Django 4.2.5 on 2023-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lessonview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='Default Lesson Name', max_length=255),
        ),
    ]
