# Generated by Django 4.2.5 on 2023-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='end_time',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
