# Generated by Django 4.2.5 on 2023-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_lessonview_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
