# Generated by Django 4.2.5 on 2023-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_lessonview_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='time_watched',
            field=models.FloatField(null=True),
        ),
    ]
