# Generated by Django 4.2.5 on 2023-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_lessonview_time_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(null=True),
        ),
    ]
